version: '3.8'

# Development overrides for docker-compose.yml
services:
  backend:
    environment:
      - DEBUG=True
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - /app/__pycache__
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: ["npm", "start"]


